name: "Continuous Deploy"

on:
    push:
        branches:
            - second-branch


jobs:
    pull_and_run_code:
        if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.outputs.branch == 'second-branch' }}
        runs-on: self-hosted
        steps:
            - name: "stop the container"
              run: "docker stop test-calc || true"
            
            - name: "Remove the container test-calc"
              run: docker rm test-calc || true
            
            - name: "get the code from Docker Hub"
              run: docker pull monyslim/apper-image:2
            
            - name: "run the image as a container"
              run: docker run -d -p 3004:3000 --name test-calc monyslim/apper-image:2