name: CI
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate random version number
        run: |
          APP_VERSION=$RANDOM
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          echo $APP_VERSION > app_version.txt

      - name: Debug - Check app_version.txt
        run: cat app_version.txt

      - name: Upload APP_VERSION artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-version
          path: app_version.txt

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install Dependencies
        run: npm install

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        env:
          IMAGE_NAME: test-image
          USERNAME: monyslim
        run: |
          echo ${{ env.APP_VERSION }}
          docker build -t $USERNAME/$IMAGE_NAME:${{ env.APP_VERSION }} .

      - name: Push Docker image to Docker Hub
        env:
          IMAGE_NAME: test-image
          USERNAME: monyslim
        run: |
          docker push $USERNAME/$IMAGE_NAME:${{ env.APP_VERSION }}
