# Workflow name
name: CI/CD Pipeline

# Define when to trigger the Workflow
on:
  push:
    branches:
      - master

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Print greeting
        run: echo "Building Docker image on master branch!!"

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        env:
          IMAGE_NAME: apper-image
          VERSION: 1
          USERNAME: monyslim
        run: docker build -t $username/$image_name:$version .
      - name: push the image
        env:
            IMAGE_NAME: apper-image
            VERSION: 1
            USERNAME: monyslim
        run: |
            docker push $username/$image_name:$version