# Workflow name
name: CI/CD Pipeline

# Define when to trigger the Workflow
on:
  push:
    branches:
      - second-branch

jobs:
  run-the-image:
    if: ${{ github.ref_name == 'second-branch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Runs on second-branch!!"
      - name: Check out code
        uses: actions/checkout@v2

      - name: Print greeting
        run: echo "Building Docker image on second-branch!!"

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        env:
          IMAGE_NAME: apper-image
          VERSION: 2
          USERNAME: monyslim
        run: docker build -t $USERNAME/$IMAGE_NAME:$VERSION .
      - name: push the image
        env:
            IMAGE_NAME: apper-image
            VERSION: 2
            USERNAME: monyslim
        run: |
            docker push $USERNAME/$IMAGE_NAME:$VERSION