# Workflow name
name: CI/CD Pipeline

# Define when to trigger the Workflow
on:
  push:
    branches:
      - second-branch

jobs:
  run-the-image:
    if: ${{ github.ref_name == 'second-branch' }}
    runs-on: self-hosted
    steps:
      - name: Print greeting
        run: |
          echo "Runs on second-branch!!"
      - name: Check out code
        uses: actions/checkout@v2

      - name: Print greeting
        run: echo "Building Docker image on second-branch!!"

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
            if [ "${GITHUB_REF##*/}" == "second-branch" ]; then
              echo "Building Docker image on second-branch"
              docker build -t monyslim/apper-image:2 .
              docker push monyslim/apper-image:2
            elif [ "${GITHUB_REF##*/}" == "master" ]; then
              echo "Building Docker image on master"
              docker build -t monyslim/apper-image:1 .
              docker push monyslim/apper-image:1
            fi